export const TOKEN_KEY = 'tastyToken'
export const TOKEN_EXPIRE_DATE = 'tastyToken_expire'
export const REFRESH_TOKEN_KEY = 'tastyRefreshToken'
export const REFRESH_TOKEN_EXPIRE_DATE = 'tastyRefreshToken_expire'
export const CURRENT_USER = 'currentUser'
